# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-imx8mp-isp"
BBFILE_PATTERN_meta-imx8mp-isp = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-imx8mp-isp = "9"

LAYERDEPENDS_meta-imx8mp-isp = "core"
LAYERSERIES_COMPAT_meta-imx8mp-isp = "walnascar scarthgap nanbield mickledore"
